:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\Corp.Prod.Area.Sub
dotnet build src\Corp.Prod.Area.Sub
echo Now, run the following to start the project: dotnet run -p src\Corp.Prod.Area.Sub\Corp.Prod.Area.Sub.csproj --launch-profile web.
echo.
