/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.22.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Corp.Prod.BusinessLogic.Entities;
using Corp.Prod.BusinessLogic.Interfaces;

namespace Corp.Prod.BusinessLogic.Entities
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Truck : ITruckLogic
    {
        /// <summary>
        /// GeoJSON (https://geojson.org/) of the area covered by the truck.
        /// </summary>
        /// <value>GeoJSON (https://geojson.org/) of the area covered by the truck.</value>
        [Required]
        [DataMember(Name="regionGeoJson", EmitDefaultValue=false)]
        public string RegionGeoJson { get; set; }

        /// <summary>
        /// The truck&#39;s number plate.
        /// </summary>
        /// <value>The truck&#39;s number plate.</value>
        [Required]
        [DataMember(Name="numberPlate", EmitDefaultValue=false)]
        public string NumberPlate { get; set; }

    }
}
