/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.22.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace Corp.Prod.DataAccess.Entities
{ 
    /// <summary>
    /// 
    /// </summary>
    public partial class Truck : Hop
    {
        /// <summary>
        /// GeoJSON (https://geojson.org/) of the area covered by the truck.
        /// </summary>
        /// <value>GeoJSON (https://geojson.org/) of the area covered by the truck.</value>
        public NetTopologySuite.Geometries.Geometry Region { get; set; }

        /// <summary>
        /// The truck&#39;s number plate.
        /// </summary>
        /// <value>The truck&#39;s number plate.</value>
        public string NumberPlate { get; set; }

    }
}
