/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.22.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Corp.Prod.DataAccess.Entities
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class WarehouseNextHops 
    {
        /// <summary>
        /// Gets or Sets TraveltimeMins
        /// </summary>
        public int TraveltimeMins { get; set; }

        /// <summary>
        /// Gets or Sets Hop
        /// </summary>
        public Hop Hop { get; set; }

    }
}
